CREATE TABLE `goods_received_lines` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`grn_id` text NOT NULL,
	`purchase_order_line_id` text NOT NULL,
	`item_id` text,
	`quantity_ordered` real NOT NULL,
	`quantity_received` real NOT NULL,
	`quantity_accepted` real NOT NULL,
	`quantity_rejected` real DEFAULT 0,
	`rejection_reason` text,
	`notes` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`grn_id`) REFERENCES `goods_received_notes`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`purchase_order_line_id`) REFERENCES `purchase_order_lines`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`item_id`) REFERENCES `inventory_items`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `goods_received_notes` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`grn_number` text NOT NULL,
	`purchase_order_id` text NOT NULL,
	`supplier_id` text NOT NULL,
	`received_date` integer NOT NULL,
	`warehouse_id` text,
	`delivery_note` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`notes` text,
	`received_by` text NOT NULL,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`supplier_id`) REFERENCES `suppliers`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`received_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `purchase_order_lines` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`purchase_order_id` text NOT NULL,
	`item_id` text,
	`description` text NOT NULL,
	`quantity` real NOT NULL,
	`quantity_received` real DEFAULT 0,
	`unit` text DEFAULT 'unit',
	`unit_price` real NOT NULL,
	`tax_rate` real DEFAULT 0,
	`discount_percent` real DEFAULT 0,
	`line_total` real NOT NULL,
	`notes` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`item_id`) REFERENCES `inventory_items`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `purchase_orders` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`order_number` text NOT NULL,
	`supplier_id` text NOT NULL,
	`requisition_id` text,
	`order_date` integer NOT NULL,
	`expected_delivery_date` integer,
	`status` text DEFAULT 'draft' NOT NULL,
	`subtotal` real NOT NULL,
	`tax_amount` real DEFAULT 0,
	`shipping_cost` real DEFAULT 0,
	`discount_amount` real DEFAULT 0,
	`total` real NOT NULL,
	`currency` text DEFAULT 'EUR',
	`payment_terms` text,
	`shipping_address` text,
	`billing_address` text,
	`notes` text,
	`internal_notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`supplier_id`) REFERENCES `suppliers`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`requisition_id`) REFERENCES `purchase_requisitions`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `purchase_requisition_lines` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`requisition_id` text NOT NULL,
	`item_id` text,
	`description` text NOT NULL,
	`quantity` real NOT NULL,
	`unit` text DEFAULT 'unit',
	`estimated_price` real,
	`estimated_total` real,
	`notes` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`requisition_id`) REFERENCES `purchase_requisitions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`item_id`) REFERENCES `inventory_items`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `purchase_requisitions` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`requisition_number` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`requested_by` text NOT NULL,
	`department_id` text,
	`priority` text DEFAULT 'medium' NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`required_date` integer,
	`approved_by` text,
	`approved_at` integer,
	`rejection_reason` text,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`requested_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`supplier_number` text NOT NULL,
	`name` text NOT NULL,
	`company_name` text,
	`email` text,
	`phone` text,
	`website` text,
	`tax_number` text,
	`address` text,
	`city` text,
	`state` text,
	`postal_code` text,
	`country` text,
	`payment_terms` text,
	`currency` text DEFAULT 'EUR',
	`credit_limit` real,
	`rating` integer,
	`notes` text,
	`active` integer DEFAULT true,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
