CREATE TABLE `fiscal_declarations` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`config_id` text NOT NULL,
	`declaration_type` text NOT NULL,
	`period` text NOT NULL,
	`reference_number` text,
	`external_id` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`total_amount` integer,
	`paid_amount` integer,
	`due_date` text,
	`paid_at` text,
	`declaration_data` text NOT NULL,
	`employee_count` integer,
	`receipt_url` text,
	`submission_proof` text,
	`submitted_by` text,
	`submitted_at` text,
	`notes` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`config_id`) REFERENCES `integration_configs`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`submitted_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `integration_configs` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`provider_category` text NOT NULL,
	`name` text NOT NULL,
	`credentials` text NOT NULL,
	`settings` text,
	`environment` text DEFAULT 'production' NOT NULL,
	`is_enabled` integer DEFAULT false NOT NULL,
	`is_default` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'pending_setup' NOT NULL,
	`last_tested_at` text,
	`last_error_message` text,
	`created_by` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `integration_transactions` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`config_id` text NOT NULL,
	`type` text NOT NULL,
	`action` text NOT NULL,
	`external_id` text,
	`internal_ref` text,
	`ref_type` text,
	`ref_id` text,
	`status` text NOT NULL,
	`status_message` text,
	`amount` integer,
	`currency` text DEFAULT 'TND',
	`fees` integer,
	`request_payload` text,
	`response_payload` text,
	`error_code` text,
	`error_message` text,
	`metadata` text,
	`ip_address` text,
	`user_agent` text,
	`created_at` text NOT NULL,
	`completed_at` text,
	`duration` integer,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`config_id`) REFERENCES `integration_configs`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `integration_webhook_events` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text,
	`config_id` text,
	`provider_id` text NOT NULL,
	`event_type` text NOT NULL,
	`payload` text NOT NULL,
	`signature` text,
	`verified` integer DEFAULT false,
	`processed` integer DEFAULT false NOT NULL,
	`processed_at` text,
	`processing_error` text,
	`transaction_id` text,
	`ip_address` text,
	`user_agent` text,
	`headers` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`config_id`) REFERENCES `integration_configs`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`transaction_id`) REFERENCES `integration_transactions`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `payment_transactions` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`transaction_id` text NOT NULL,
	`payment_method` text,
	`payment_url` text,
	`customer_phone` text,
	`customer_email` text,
	`paid_at` text,
	`refunded_at` text,
	`refund_amount` integer,
	`refund_reason` text,
	`invoice_id` text,
	`order_id` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`transaction_id`) REFERENCES `integration_transactions`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `shipping_transactions` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`transaction_id` text NOT NULL,
	`tracking_number` text,
	`service_type` text,
	`label_url` text,
	`sender_address` text,
	`recipient_address` text,
	`weight` integer,
	`dimensions` text,
	`description` text,
	`cod_amount` integer,
	`cod_collected` integer DEFAULT false,
	`cod_collected_at` text,
	`estimated_delivery` text,
	`actual_delivery` text,
	`delivery_status` text,
	`delivery_proof` text,
	`order_id` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`transaction_id`) REFERENCES `integration_transactions`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `sms_transactions` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`transaction_id` text NOT NULL,
	`recipient_phone` text NOT NULL,
	`sender_id` text,
	`message` text NOT NULL,
	`message_length` integer,
	`segments` integer DEFAULT 1,
	`delivered_at` text,
	`delivery_status` text,
	`unit_cost` integer,
	`template_id` text,
	`template_name` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`transaction_id`) REFERENCES `integration_transactions`(`id`) ON UPDATE no action ON DELETE cascade
);
